In [1]:
import requests
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import datetime as dt
import itertools
import json
import pymysql
import geopandas as gpd
import yaml
import os

In [2]:
temp_gdf = gpd.read_file("./sejong/Population/Population_Sample.shp")

In [21]:
temp_gdf

,gid,lbl,val,disabled,older_adul,total,geometry
0,??¤?°?787347,26.00,26.0,5,6,11,"POLYGON ((127.26213 36.50974, 127.26213 36.510..."
1,??¤?°?779326,19.00,19.0,7,6,13,"POLYGON ((127.25325 36.49079, 127.25325 36.491..."
2,??¤?°?781337,21.00,21.0,6,7,13,"POLYGON ((127.25546 36.50071, 127.25545 36.501..."
3,??¤?°?772353,22.00,22.0,5,8,13,"POLYGON ((127.24536 36.51512, 127.24536 36.516..."
4,??¤?°?776339,N/A,0.0,6,6,12,"POLYGON ((127.24987 36.5025, 127.24986 36.5034..."
...,...,...,...,...,...,...,...
1401,??¤?°?796337,None,NaN,7,7,14,"POLYGON ((127.27221 36.50075, 127.2722 36.5016..."
1402,??¤?°?802334,None,NaN,5,8,13,"POLYGON ((127.27891 36.49805, 127.27891 36.498..."
1403,??¤?°?793337,None,NaN,7,5,12,"POLYGON ((127.26886 36.50074, 127.26885 36.501..."
1404,??¤?°?774320,None,NaN,5,4,9,"POLYGON ((127.24769 36.48537, 127.24769 36.486..."
1405,??¤?°?792354,None,NaN,8,7,15,"POLYGON ((127.26769 36.51606, 127.26769 36.516..."

In [7]:
current_gdf = gpd.read_file("./population/Population_grid_re_re.shp")
current_gdf

,id,left,top,right,bottom,row_index,col_index,geometry
0,1.0,936201.5173,1.919855e+06,936301.5173,1.919755e+06,0.0,0.0,"POLYGON ((936201.517 1919854.538, 936301.517 1..."
1,2.0,936201.5173,1.919755e+06,936301.5173,1.919655e+06,1.0,0.0,"POLYGON ((936201.517 1919754.538, 936301.517 1..."
2,3.0,936201.5173,1.919655e+06,936301.5173,1.919555e+06,2.0,0.0,"POLYGON ((936201.517 1919654.538, 936301.517 1..."
3,4.0,936201.5173,1.919555e+06,936301.5173,1.919455e+06,3.0,0.0,"POLYGON ((936201.517 1919554.538, 936301.517 1..."
4,5.0,936201.5173,1.919455e+06,936301.5173,1.919355e+06,4.0,0.0,"POLYGON ((936201.517 1919454.538, 936301.517 1..."
...,...,...,...,...,...,...,...,...
6075,6076.0,942501.5173,1.910855e+06,942601.5173,1.910755e+06,90.0,63.0,"POLYGON ((942501.517 1910854.538, 942601.517 1..."
6076,6077.0,942501.5173,1.910755e+06,942601.5173,1.910655e+06,91.0,63.0,"POLYGON ((942501.517 1910754.538, 942601.517 1..."
6077,6078.0,942501.5173,1.910655e+06,942601.5173,1.910555e+06,92.0,63.0,"POLYGON ((942501.517 1910654.538, 942601.517 1..."
6078,6079.0,942501.5173,1.910555e+06,942601.5173,1.910455e+06,93.0,63.0,"POLYGON ((942501.517 1910554.538, 942601.517 1..."
6079,6080.0,942501.5173,1.910455e+06,942601.5173,1.910355e+06,94.0,63.0,"POLYGON ((942501.517 1910454.538, 942601.517 1..."

In [8]:
print(current_gdf.crs)

EPSG:5179

In [9]:
gdf_4326 = current_gdf.to_crs(epsg=4326)

In [10]:
gdf_4326

,id,left,top,right,bottom,row_index,col_index,geometry
0,1.0,936201.5173,1.919855e+06,936301.5173,1.919755e+06,0.0,0.0,"POLYGON ((126.78037 37.27543, 126.7815 37.2754..."
1,2.0,936201.5173,1.919755e+06,936301.5173,1.919655e+06,1.0,0.0,"POLYGON ((126.78038 37.27452, 126.78151 37.274..."
2,3.0,936201.5173,1.919655e+06,936301.5173,1.919555e+06,2.0,0.0,"POLYGON ((126.78039 37.27362, 126.78152 37.273..."
3,4.0,936201.5173,1.919555e+06,936301.5173,1.919455e+06,3.0,0.0,"POLYGON ((126.7804 37.27272, 126.78153 37.2727..."
4,5.0,936201.5173,1.919455e+06,936301.5173,1.919355e+06,4.0,0.0,"POLYGON ((126.78041 37.27182, 126.78153 37.271..."
...,...,...,...,...,...,...,...,...
6075,6076.0,942501.5173,1.910855e+06,942601.5173,1.910755e+06,90.0,63.0,"POLYGON ((126.85212 37.19471, 126.85325 37.194..."
6076,6077.0,942501.5173,1.910755e+06,942601.5173,1.910655e+06,91.0,63.0,"POLYGON ((126.85213 37.19381, 126.85326 37.193..."
6077,6078.0,942501.5173,1.910655e+06,942601.5173,1.910555e+06,92.0,63.0,"POLYGON ((126.85214 37.19291, 126.85327 37.192..."
6078,6079.0,942501.5173,1.910555e+06,942601.5173,1.910455e+06,93.0,63.0,"POLYGON ((126.85215 37.19201, 126.85327 37.192..."
6079,6080.0,942501.5173,1.910455e+06,942601.5173,1.910355e+06,94.0,63.0,"POLYGON ((126.85215 37.19111, 126.85328 37.191..."

In [13]:
gdf_4326

,id,left,top,right,bottom,row_index,col_index,geometry
0,1.0,936201.5173,1.919855e+06,936301.5173,1.919755e+06,0.0,0.0,"POLYGON ((126.78037 37.27543, 126.7815 37.2754..."
1,2.0,936201.5173,1.919755e+06,936301.5173,1.919655e+06,1.0,0.0,"POLYGON ((126.78038 37.27452, 126.78151 37.274..."
2,3.0,936201.5173,1.919655e+06,936301.5173,1.919555e+06,2.0,0.0,"POLYGON ((126.78039 37.27362, 126.78152 37.273..."
3,4.0,936201.5173,1.919555e+06,936301.5173,1.919455e+06,3.0,0.0,"POLYGON ((126.7804 37.27272, 126.78153 37.2727..."
4,5.0,936201.5173,1.919455e+06,936301.5173,1.919355e+06,4.0,0.0,"POLYGON ((126.78041 37.27182, 126.78153 37.271..."
...,...,...,...,...,...,...,...,...
6075,6076.0,942501.5173,1.910855e+06,942601.5173,1.910755e+06,90.0,63.0,"POLYGON ((126.85212 37.19471, 126.85325 37.194..."
6076,6077.0,942501.5173,1.910755e+06,942601.5173,1.910655e+06,91.0,63.0,"POLYGON ((126.85213 37.19381, 126.85326 37.193..."
6077,6078.0,942501.5173,1.910655e+06,942601.5173,1.910555e+06,92.0,63.0,"POLYGON ((126.85214 37.19291, 126.85327 37.192..."
6078,6079.0,942501.5173,1.910555e+06,942601.5173,1.910455e+06,93.0,63.0,"POLYGON ((126.85215 37.19201, 126.85327 37.192..."
6079,6080.0,942501.5173,1.910455e+06,942601.5173,1.910355e+06,94.0,63.0,"POLYGON ((126.85215 37.19111, 126.85328 37.191..."

In [12]:
gdf_4326.to_file("./population/grid_100m_4326.shp", driver="ESRI Shapefile", encoding="utf-8")

In [22]:
rng = np.random.default_rng(254)
gdf_4326['disabled'] = rng.integers(5, 11, size=len(gdf_4326))

rng = np.random.default_rng(3151)
gdf_4326['older_adul'] = rng.integers(8, 15, size=len(gdf_4326))

In [23]:
gdf_4326

,id,left,top,right,bottom,row_index,col_index,geometry,disabled,older_adul
0,1.0,936201.5173,1.919855e+06,936301.5173,1.919755e+06,0.0,0.0,"POLYGON ((126.78037 37.27543, 126.7815 37.2754...",6,11
1,2.0,936201.5173,1.919755e+06,936301.5173,1.919655e+06,1.0,0.0,"POLYGON ((126.78038 37.27452, 126.78151 37.274...",7,11
2,3.0,936201.5173,1.919655e+06,936301.5173,1.919555e+06,2.0,0.0,"POLYGON ((126.78039 37.27362, 126.78152 37.273...",10,8
3,4.0,936201.5173,1.919555e+06,936301.5173,1.919455e+06,3.0,0.0,"POLYGON ((126.7804 37.27272, 126.78153 37.2727...",8,8
4,5.0,936201.5173,1.919455e+06,936301.5173,1.919355e+06,4.0,0.0,"POLYGON ((126.78041 37.27182, 126.78153 37.271...",9,14
...,...,...,...,...,...,...,...,...,...,...
6075,6076.0,942501.5173,1.910855e+06,942601.5173,1.910755e+06,90.0,63.0,"POLYGON ((126.85212 37.19471, 126.85325 37.194...",6,14
6076,6077.0,942501.5173,1.910755e+06,942601.5173,1.910655e+06,91.0,63.0,"POLYGON ((126.85213 37.19381, 126.85326 37.193...",7,13
6077,6078.0,942501.5173,1.910655e+06,942601.5173,1.910555e+06,92.0,63.0,"POLYGON ((126.85214 37.19291, 126.85327 37.192...",10,13
6078,6079.0,942501.5173,1.910555e+06,942601.5173,1.910455e+06,93.0,63.0,"POLYGON ((126.85215 37.19201, 126.85327 37.192...",5,9
6079,6080.0,942501.5173,1.910455e+06,942601.5173,1.910355e+06,94.0,63.0,"POLYGON ((126.85215 37.19111, 126.85328 37.191...",7,12

In [24]:
gdf_4326['total'] = gdf_4326['disabled'] + gdf_4326['older_adul']
gdf_4326

,id,left,top,right,bottom,row_index,col_index,geometry,disabled,older_adul,total
0,1.0,936201.5173,1.919855e+06,936301.5173,1.919755e+06,0.0,0.0,"POLYGON ((126.78037 37.27543, 126.7815 37.2754...",6,11,17
1,2.0,936201.5173,1.919755e+06,936301.5173,1.919655e+06,1.0,0.0,"POLYGON ((126.78038 37.27452, 126.78151 37.274...",7,11,18
2,3.0,936201.5173,1.919655e+06,936301.5173,1.919555e+06,2.0,0.0,"POLYGON ((126.78039 37.27362, 126.78152 37.273...",10,8,18
3,4.0,936201.5173,1.919555e+06,936301.5173,1.919455e+06,3.0,0.0,"POLYGON ((126.7804 37.27272, 126.78153 37.2727...",8,8,16
4,5.0,936201.5173,1.919455e+06,936301.5173,1.919355e+06,4.0,0.0,"POLYGON ((126.78041 37.27182, 126.78153 37.271...",9,14,23
...,...,...,...,...,...,...,...,...,...,...,...
6075,6076.0,942501.5173,1.910855e+06,942601.5173,1.910755e+06,90.0,63.0,"POLYGON ((126.85212 37.19471, 126.85325 37.194...",6,14,20
6076,6077.0,942501.5173,1.910755e+06,942601.5173,1.910655e+06,91.0,63.0,"POLYGON ((126.85213 37.19381, 126.85326 37.193...",7,13,20
6077,6078.0,942501.5173,1.910655e+06,942601.5173,1.910555e+06,92.0,63.0,"POLYGON ((126.85214 37.19291, 126.85327 37.192...",10,13,23
6078,6079.0,942501.5173,1.910555e+06,942601.5173,1.910455e+06,93.0,63.0,"POLYGON ((126.85215 37.19201, 126.85327 37.192...",5,9,14
6079,6080.0,942501.5173,1.910455e+06,942601.5173,1.910355e+06,94.0,63.0,"POLYGON ((126.85215 37.19111, 126.85328 37.191...",7,12,19

In [25]:
gdf_4326['gid'] = gdf_4326['id']
gdf_4326

,id,left,top,right,bottom,row_index,col_index,geometry,disabled,older_adul,total,gid
0,1.0,936201.5173,1.919855e+06,936301.5173,1.919755e+06,0.0,0.0,"POLYGON ((126.78037 37.27543, 126.7815 37.2754...",6,11,17,1.0
1,2.0,936201.5173,1.919755e+06,936301.5173,1.919655e+06,1.0,0.0,"POLYGON ((126.78038 37.27452, 126.78151 37.274...",7,11,18,2.0
2,3.0,936201.5173,1.919655e+06,936301.5173,1.919555e+06,2.0,0.0,"POLYGON ((126.78039 37.27362, 126.78152 37.273...",10,8,18,3.0
3,4.0,936201.5173,1.919555e+06,936301.5173,1.919455e+06,3.0,0.0,"POLYGON ((126.7804 37.27272, 126.78153 37.2727...",8,8,16,4.0
4,5.0,936201.5173,1.919455e+06,936301.5173,1.919355e+06,4.0,0.0,"POLYGON ((126.78041 37.27182, 126.78153 37.271...",9,14,23,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6075,6076.0,942501.5173,1.910855e+06,942601.5173,1.910755e+06,90.0,63.0,"POLYGON ((126.85212 37.19471, 126.85325 37.194...",6,14,20,6076.0
6076,6077.0,942501.5173,1.910755e+06,942601.5173,1.910655e+06,91.0,63.0,"POLYGON ((126.85213 37.19381, 126.85326 37.193...",7,13,20,6077.0
6077,6078.0,942501.5173,1.910655e+06,942601.5173,1.910555e+06,92.0,63.0,"POLYGON ((126.85214 37.19291, 126.85327 37.192...",10,13,23,6078.0
6078,6079.0,942501.5173,1.910555e+06,942601.5173,1.910455e+06,93.0,63.0,"POLYGON ((126.85215 37.19201, 126.85327 37.192...",5,9,14,6079.0
6079,6080.0,942501.5173,1.910455e+06,942601.5173,1.910355e+06,94.0,63.0,"POLYGON ((126.85215 37.19111, 126.85328 37.191...",7,12,19,6080.0

In [26]:
gdf_4326.columns

Index(['id', 'left', 'top', 'right', 'bottom', 'row_index', 'col_index',
       'geometry', 'disabled', 'older_adul', 'total', 'gid'],
      dtype='object')

In [27]:
gdf_4326_final = gdf_4326[['gid','disabled', 'older_adul', 'total', 'geometry']]
gdf_4326_final

,gid,disabled,older_adul,total,geometry
0,1.0,6,11,17,"POLYGON ((126.78037 37.27543, 126.7815 37.2754..."
1,2.0,7,11,18,"POLYGON ((126.78038 37.27452, 126.78151 37.274..."
2,3.0,10,8,18,"POLYGON ((126.78039 37.27362, 126.78152 37.273..."
3,4.0,8,8,16,"POLYGON ((126.7804 37.27272, 126.78153 37.2727..."
4,5.0,9,14,23,"POLYGON ((126.78041 37.27182, 126.78153 37.271..."
...,...,...,...,...,...
6075,6076.0,6,14,20,"POLYGON ((126.85212 37.19471, 126.85325 37.194..."
6076,6077.0,7,13,20,"POLYGON ((126.85213 37.19381, 126.85326 37.193..."
6077,6078.0,10,13,23,"POLYGON ((126.85214 37.19291, 126.85327 37.192..."
6078,6079.0,5,9,14,"POLYGON ((126.85215 37.19201, 126.85327 37.192..."
6079,6080.0,7,12,19,"POLYGON ((126.85215 37.19111, 126.85328 37.191..."

In [28]:
gdf_4326_final.to_file("./population/Population_Sample.shp", driver="ESRI Shapefile", encoding="utf-8")